spring:
  application:
    name: PortalWebAdmin
  thymeleaf:
    cache: true # false : 서버 재시작 없이 새로고침.  개발서버 이상부터는 true로 설정.
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: XHTML
    prefix: /WEB-INF/views/
    suffix: .html
    # template-resolver-order:
    # view-names:
  http:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}
  servlet:
    multipart:
      enabled: ${spring.http.multipart.enabled}
      max-file-size: ${spring.http.multipart.max-file-size}
      max-request-size: ${spring.http.multipart.max-request-size}
      location: ${spring.http.multipart.location}
  main:
    allow-bean-definition-overriding: true

server:
  port: 8090

datasource:
  hikari:
    maximum-pool-size: 50
  cfg:
    url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/webconfig
    username: root # YOUR UAA PORTAL DB ACCOUNT
    password: 'PASSWORD' # YOUR PORTAL DB PASSWORD
    ddl-auto: none
    naming:
      strategy: org.hibernate.dialect.MySQL5Dialect

paasta:
  portal:
    api:
      authorization:
        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
      zuulUrl:
        cfapi: http://XXX.XXX.XXX.XXX:2225/portalapi #YOUR GATEWAY SERVICE DEV SETTING(ACTIVE INFORMATION)
        commonapi: http://XXX.XXX.XXX.XXX:2225/commonapi #YOUR GATEWAY SERVICE DEV SETTING(ACTIVE INFORMATION)
        storageapi: http://XXX.XXX.XXX.XXX:2225/storageapi #YOUR GATEWAY SERVICE DEV SETTING(ACTIVE INFORMATION)
    storageapi:
      type: swift

logging:
  level:
    ROOT: INFO
  file:
    path: classpath:logback-spring.xml
    name: logs/application.log
