spring:
  application:
    name: PortalWebAdmin
  thymeleaf:
    cache: true # false : 서버 재시작 없이 새로고침.  개발서버 이상부터는 true로 설정.
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: XHTML
    prefix: /WEB-INF/views/
    suffix: .html
    # template-resolver-order:
    # view-names:
  http:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}
  servlet:
    multipart:
      enabled: ${spring.http.multipart.enabled}
      max-file-size: ${spring.http.multipart.max-file-size}
      max-request-size: ${spring.http.multipart.max-request-size}
      location: ${spring.http.multipart.location}
  main:
    allow-bean-definition-overriding: true

server:
  port: 8090

paasta:
  portal:
    api:
      authorization:
        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
      zuulUrl:
        cfapi: http://172.30.200.29:2225/portalapi
        commonapi: http://172.30.200.29:2225/commonapi
        storageapi: http://172.30.200.29:2225/storageapi
    storageapi:
      type: swift
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.30.200.32:2221/eureka/ #YOUR LOCAL TEST SETTING
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ROOT: INFO
  file:
    path: classpath:logback-spring.xml
    name: logs/application.log
